pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }
        stage('Build') {
            steps {
                echo 'Building the project...'
                dir('springboot/spring-boot-userdir-app') {
                    sh 'mvn clean package'
                }
            }
        }
        stage('Docker Build') {
            steps {
                echo 'Building Docker image...'
                dir('springboot/spring-boot-userdir-app') {
                    sh 'docker build -t vvtl8an/myapp:latest .'
                }
            }
        }
        stage('Docker Push') {
            steps {
                echo 'Pushing Docker image to Docker Hub...'
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    dir('springboot/spring-boot-userdir-app') {
                        sh '''
                            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                            docker push vvtl8an/myapp:latest
                            docker logout
                        '''
                    }
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                dir('springboot/spring-boot-userdir-app') {
                    sh 'mvn test'
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}