pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                checkout scm
            }
        }
        stage('Build') {
            steps {
                echo 'Building the project...'
                dir('springboot/spring-boot-userdir-app') {
                    sh 'mvn clean package'
                }
            }
        }
        stage('Docker Build') {
            steps {
                echo 'Building Docker image...'
                dir('springboot/spring-boot-userdir-app') {
                    sh 'docker build -t myapp:latest .'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                dir('springboot/spring-boot-userdir-app') {
                    sh 'mvn test'
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline finished.'
        }
    }
}